#!/bin/sh
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        --terraform-output)
            shift # past argument
            terraform_output="$1"
            ;;
    esac
    shift
done

python3 -m pytest /home/tivo/bin/tests -s \
            --terraform_output $terraform_output \
            --log_level DEBUG \
            --log_path /testlogs/ \
            --junitxml=/testlogs/functional_test_results.xml \
            --tb=short \
            --show-capture=no
